name: DemocraticSleep
version: 0.2.0
main: io.github.gabehowe.democraticsleep.DemocraticSleep
api-version: 1.16
authors: [ gabehowe ]
description: allows players to vote to skip the night
website: gabehowe.github.io
commands:
  sleepvoteyes:
    description: votes yes on sleep votes
    usage: /<command>
    aliases: [sy, sleepyes]
  sleepvoteno:
    description: votes no on sleep votes
    usage: /<command>
    aliases: [sn, sleepno]
